### ISSUE TITLE
Add support for recursive source -> target generation

### ISSUE THREAD

**Issue by Avataw** [StephanHCB/go-generator-cli#17]
It would be great to be able to recursively add a whole folder.

Something like: 
```yaml
  - source: "templates/some_folder/*"
    target: "some_folder"
```

**Comment by StephanHCB** [comment]
This is actually already somewhat supported, provided there is a limit to how deep the folder tree goes, and assuming you give your template files a common extension.

```
  - source: '{{ .file }}'
    target: 'output/{{ .file | replace ".tmpl" "" }}'
    with_files:
      - 'templates/some_folder/*.tmpl'
      - 'templates/some_folder/*/*.tmpl'
      - 'templates/some_folder/*/*/*.tmpl'
      - 'templates/some_folder/*/*/*/*.tmpl'
      - 'templates/some_folder/*/*/*/*/*.tmpl'
```
Unfortunately, golang package filepath does not support `**` in its Glob function, that's why you have to spell out the nesting levels, and it's limited to 4 directory levels I believe.

The feature is mentioned briefly in the readme, look for `with_files`.

Support for ** would be great, though, so I'll keep this issue open. Will have to go on the lookout for a better Glob function than filepath.Glob.
